# Generated by Django 4.1 on 2022-08-22 22:44

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('insti', models.CharField(max_length=100, verbose_name='Institución')),
                ('descr', models.CharField(max_length=100, verbose_name='Web')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider', verbose_name='Imagen')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('descr', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('activ', models.CharField(blank=True, max_length=6, null=True, verbose_name='active')),
                ('perso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service', verbose_name='Icono')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('descr', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('perso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('1', 'Personal'), ('2', 'Cliente'), ('3', 'Privado')], default='1', max_length=1, verbose_name='Clase')),
                ('image', models.ImageField(blank=True, null=True, upload_to='folio', verbose_name='Icono')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('descr', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('enlac', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enlace')),
                ('youtb', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Youtube')),
                ('perso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=100, verbose_name='Font-awesome')),
                ('descr', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('perso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.person')),
            ],
        ),
    ]
